name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        node: [14]

    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} node@${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Set node to ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Test
        run: npm test
